server:
  port: 8082


spring:
  application:
    name: Employee

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
    password: omjee123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  info:
    app:
      name: Employee Management System
      description: Spring Boot Employee Project with Actuator
      version: 1.0.0
      owner: Om Jee Ray
